apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-demo-run-
spec:
  pipelineRef:
    name: tekton-demo
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: workdir
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
